### ISSUE TITLE
Pre-existing files with wonky filenames in /dev/shm cause panics in inventory of rings at startup.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/rust-ringmaster#1]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 16, error_len: Some(1) }', /user/fox/.cargo/registry/src/github.com-1ecc6299db9ec823/nscldaq_ringbuffer-0.6.4/src/lib.rs:137:83
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: nscldaq_ringbuffer::ringbuffer::RingBufferMap::new
   4: nscldaq_ringmaster::rings::inventory::inventory::inventory_rings
   5: nscldaq_ringmaster::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
Attached log.txt file shows an ls -alb of a /dev/shm that expresses this bug.

**Comment by rfoxkendo** [comment]
This is actuall issue 1 of the rust-ringbuffer respository ..so closing here.
